/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DAOEmprestimo;
import Modelo.Emprestimo;
import Tabelas.TabelaEmprestimo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class TelaEmprestimos extends javax.swing.JFrame {

    int simulaIdFuncionario = 1;
    MaskFormatter mfData;
    private boolean editarDeletar;
    private TabelaEmprestimo modelo;
    private DAOEmprestimo daoEmprestimo;
    /**
     * Creates new form TelaEmprestimos
     */
    public TelaEmprestimos() {
        try{
           mfData = new MaskFormatter("##/##/####");
        }catch(ParseException ex){
            System.out.println("Ocorreu um erro na criação da máscara de data");
        }
        
        initComponents();
        
        meuInitComponents();
    }
    
    private void meuInitComponents(){
       modelo = new TabelaEmprestimo();
       daoEmprestimo = new DAOEmprestimo();
       
       tableEmprestimos.setModel(modelo);
       
       habilitaDesabilitaEditarDeletar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmprestimos = new javax.swing.JTable();
        txtData = new javax.swing.JFormattedTextField(mfData);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empréstimos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID do usuário:");

        txtIdUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID do Livro:");

        txtIdLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Data do Empréstimo:");

        btnInserir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tableEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmprestimosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmprestimos);

        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtIdUsuario)
                    .addComponent(btnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdLivro)
                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String data = txtData.getText();
        String idUsuario = txtIdUsuario.getText();
        String idLivro = txtIdLivro.getText();
        
        if(data.isBlank() || idUsuario.isBlank() || idLivro.isBlank()){
            JOptionPane.showMessageDialog(this, "Todos os campos devem estar preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            int idUser = Integer.parseInt(idUsuario);
            int idBook = Integer.parseInt(idLivro);
            Date date = criaData(data);
            
            Emprestimo emprestimo = new Emprestimo(simulaIdFuncionario, idUser, idBook, date);
            this.modelo.addEmprestimo(emprestimo);
        }catch(Exception ex){
            System.err.println("\nExcecao: " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Digite apenas números para os ids.", "Erro",JOptionPane.ERROR_MESSAGE);
        }

        reiniciaForm();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        /*int idUsuario = (int) tableUsuarios.getModel().getValueAt(tableUsuarios.getSelectedRow(), 3);

        //Gerando o funcionario antigo
        Usuario antigo = daoUsuario.localizar(idUsuario);

        //Criando o novoobjeto autor
        String regAcademico = txtRegAcademico.getText();
        String nome = txtNome.getText();
        String sobrenome = txtSobrenome.getText();
        if(regAcademico.isBlank() || nome.isBlank() || sobrenome.isBlank()){
            JOptionPane.showMessageDialog(this, "Todos os campos devem estar preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            int registro = Integer.parseInt(regAcademico);
            Usuario novo = new Usuario(registro, nome, sobrenome);
            this.modelo.updateUsuario(novo, antigo);
        }catch(Exception ex){
            System.err.println("\nExcecao: " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Digite apenas números para o registro acadêmico.", "Erro",JOptionPane.ERROR_MESSAGE);
        }
        reiniciaForm();*/
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        /*int idUsuario = (int) tableUsuarios.getModel().getValueAt(tableUsuarios.getSelectedRow(), 3);
        Usuario antigo = daoUsuario.localizar(idUsuario);
        this.modelo.deletarUsuario(antigo);
        reiniciaForm();*/
    }//GEN-LAST:event_btnRemoverActionPerformed
    
    private void tableEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmprestimosMouseClicked
        /*//Lendo a linha e coluna selecionada
        int linhaSelecionada = tableUsuarios.getSelectedRow();

        //Alterando o texto do textField
        String nome = (String) tableUsuarios.getModel().getValueAt(linhaSelecionada, 0);
        String sobrenome = (String) tableUsuarios.getModel().getValueAt(linhaSelecionada, 1);
        int regAcademico = (int) tableUsuarios.getModel().getValueAt(linhaSelecionada, 2);

        txtNome.setText(nome);
        txtSobrenome.setText(sobrenome);
        txtRegAcademico.setText(""+regAcademico);

        habilitaDesabilitaEditarDeletar();*/
    }//GEN-LAST:event_tableEmprestimosMouseClicked

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        try{
            Date date = sdf.parse(txtData.getText());
            txtData.setValue(sdf.format(date));
        }catch(ParseException ex){
            txtData.setFocusLostBehavior(JFormattedTextField.PERSIST);
            txtData.setText("");
            txtData.setValue(null);
        }
    }//GEN-LAST:event_txtDataFocusLost

    private Date criaData(String data){
        String dataStr[] = data.split("/");
        
        int dia = Integer.parseInt(dataStr[0]);
        int mes = Integer.parseInt(dataStr[1]);
        int ano = Integer.parseInt(dataStr[2]);
        
        return new Date(ano, mes, dia);
    }
    
    private void reiniciaForm(){
        txtData.setText("");
        txtIdUsuario.setText("");
        txtIdLivro.setText("");
        
        habilitaDesabilitaEditarDeletar();
        txtIdUsuario.requestFocus();
        tableEmprestimos.getSelectionModel().clearSelection();
    }
    
    private void habilitaDesabilitaEditarDeletar(){
        editarDeletar = tableEmprestimos.getSelectedRowCount() != 0;
       
       btnEditar.setEnabled(editarDeletar);
       btnRemover.setEnabled(editarDeletar);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmprestimos;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtIdLivro;
    private javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables
}
